### ISSUE TITLE
Crash when attempting to browse files of logo partition on Smash

### ISSUE THREAD

**Issue by roblabla** [DarkMatterCore/gcdumptool#12] opened 2018-12-14 21:55 UTC
While trying to browser the logo partition of Smash, I got a fatal screen. It seems to crash in the getGameCardTitleIDAndVersion function. The stacktrace and memory dump is in the zip attached here.

[gcdumptool_crash.zip](https://github.com/DarkMatterCore/gcdumptool/files/2681801/gcdumptool_crash.zip)

**Comment by DarkMatterCore** [comment] 2019-04-22 16:55
@roblabla 

Hi there. Sorry for taking so long to answer, a lot of things have happened in my personal life in the past few months, and they have kept me busy enough to stop browsing the Internet as much as I'd like.

This problem seems to be related to #4. Could you please try out the attached test build? I have enabled manual HFS0 partition header parsing in it, replacing the partition filesystem mounting steps through fs-srv calls. Hopefully, it should work.

[gcdumptool_test_20190422.zip](https://github.com/DarkMatterCore/gcdumptool/files/3104155/gcdumptool_test_20190422.zip)

**Comment by DarkMatterCore** [comment] 2019-04-23 05:06
This was already confirmed to be working by @fennectech using a test build with yet-to-be-pushed changes (check issue #13). I'll close this issue and make a proper release in a few hours.

If you run into other problems, please, feel free to open another issue or to reopen this one! Thanks.

**Comment by fennectech** [comment] 2019-04-23 05:07
Godspeed!

**Comment by DarkMatterCore** [comment] 2019-04-23 05:27
Fixed in d22add43bf9ab487d4faf432818a6d6fd72f733d.

**Closed** 2019-04-23 05:27 UTC
Labels: duplicate

**Comment by DarkMatterCore** [comment] 2019-04-23 11:46
@roblabla 

While we're still at it (I hope \*not\* to have lost your interest in this just yet!), I noticed you're one of the maintainers of the SwIPC project. First of all, let me thank you, because I wouldn't have been able to get the application running up to this point without all that documentation.

That being said, would you be able to give some insight regarding issue #5? I've been trying to track down that bug for a few months now and, other than pinpointing it as being the result of calling `OpenGameCardStorage` at least once, I've been unable to achieve anything else. It doesn't matter if the call itself fails or not.

Any input on this topic would be greatly appreciated.
