### ISSUE TITLE
Service initialization hangs the program on the "Please wait..." message when the console hasn't been connected to the Internet in the past while running Hekate/SX OS.

### ISSUE THREAD

**Issue by Pneumaticat** [DarkMatterCore/gcdumptool#7] opened 2018-07-02 18:25 UTC
Switch Firmware: 4.1.0
Method: Hekate (3.0)
Version: 1.0.5
Game Card: Super Mario Odyssey

Similar to #6, but I've checked my SD card and even reformatted it, and I still get this issue. I'm on Linux, and I used `mkfs.vfat -F32 -s 64 /dev/sdk1` to do so.

**Comment by DarkMatterCore** [comment] 2018-07-02 18:37
This is what @x7l7j8cc said that worked for him:

"wait i think i found the problem.. its not related to gcdumptool ... but to the microsd ... 
when i go to the Software tab in the System Settings, doesnt show any games updated, but normally on my sd i have the updates for the games...

so i try first to reformat the sd, then i will let you know."

"ive solved... i dont know what happened whatever... 
for now, i solved like this: - formatted the microsd to ntfs (because the switch created another partition) and reformatted with windows in exFAT (128kb partition size)... and still didnt worked, but after i connected to my wifi without proxy, seems like it unlocked something and finally worked"

If you want, you can try [this](https://cdn.discordapp.com/attachments/462741872670932993/462797713545887744/gcdumptool.nro) test build to see in which part is the hangup taking place for you. I have already tried to reproduce the bug many times using both FAT32 and exFAT but I haven't been able to.

**Comment by DarkMatterCore** [comment] 2018-07-02 18:37
(whoops, my mistake)

**Comment by Pneumaticat** [comment] 2018-07-02 18:45
Weird, when running the test build, I still only get the "Please wait", no extra debug information is printed.

It seems that perhaps connecting to wifi helped it work? That could be the case; I've kept my switch in airplane mode the whole time since getting it. I'll try connecting to see if that works.

**Comment by Pneumaticat** [comment] 2018-07-02 18:49
Yup, connecting to Wifi fixed it. It seems that without an internet connection, it hangs there.

**Comment by DarkMatterCore** [comment] 2018-07-02 18:50
That's even weirder, to be honest. It would mean that the crash is happening right before opening the first game card handle. The first debug message in that build is supposed to display after that.

The Wi-Fi thing suggested by @x7l7j8cc still doesn't make sense to me, but maybe is something related to Horizon. Sockets are only initialized when the update options in the main menu are selected, otherwise they're never used in the application.

**Comment by Pneumaticat** [comment] 2018-07-02 18:52
Actually, it might be more nuanced than that. I just went into Airplane mode after connecting for the first time, and the tool still opens.

I can still open the tool after restarting the OS as well.

Perhaps it needs some sort of one-time download from Nintendo‽

**Comment by DarkMatterCore** [comment] 2018-07-02 19:01
Yeah, I just tried running the application in airplane mode and it still works. This has me perplexed, to say the least.

**Comment by x7l7j8cc** [comment] 2018-07-03 19:23
i think since the is now using the ncm service, need some type of authorization, and this can be done only from internet... in fact after connected one time to wifi (without any proxy/dns) and worked the first time, you can reconnect to proxy/dns or in airplane mode... this is the strange thing, but i think its necessary due to the ncm service.

Dont know, but this is the only thing i can think off.

**Comment by DarkMatterCore** [comment] 2018-07-23 03:13
Fixed with commit 7a94da0a5c452b9080fa1fc2e9d8af82ab3637a8. Turned out to be a problem with the tie functions from the standard C library. The application is now using the time service from the Switch.

**Closed by DarkMatterCore** 2018-07-23 03:13 UTC
Labels: bug, help wanted
